


def return_words():

    alph = "qwertyuıopasdfghjklşizxcvbnm1234567890. "
    alphabet = []
    for i in alph:
        alphabet.append(i)
    replaces = {"ş": "s", "ö": "o", "ü": "u", "ğ": "g", "ı": "i", "ç": "c", "é": "e", "ū": "ü"}
    """,  # Bu karakterleri boşlukla değiştiriyor
                "₺": "tl", "✔️": " ", "✔": " ", "•": " ", "➕": " ", "—": " ", "⭐": " ", "✓": " ",
                "✅": " ", "…": " ", "☎": " ", "☑": " ", "➖": " ", "⚫": " ", "➡": " ", "’": " ", '“': " ", "♤": " ",
                "▪️": " ", "▪": " ", "➜": " ", "❗️": " ", "❗": " ", "°": " ", "° ": " ", "️": " ", "★": " ",
                "5️⃣": " ", "6️⃣": " ", "9️⃣": " ", "4️⃣": " ", "2️⃣": " ", "”": " ", "❎": " ", "✨": " ", "é": "e",
                "⚠": " ", "‘": " ", "☆": " ", "◇": " ", "٪": " ", "‼": " ", "《": " ", "》": " ", "⏲": " ", "⏱": " ",
                "×": " ", "∙": " ", "÷": " ", "√": " ", "■": " ", "▶": " ", "●": " ", "○": " ", "➤": " ", "→": " ",
                "➢": " ", "©": " ", "☄": " ", "♦": " ", "®": " ", "✏": " ", "✦": " ", "✴": " ", "❌": " ", "◾": " ",
                "►": " ", "↘": " ", "⚡": " ", "‰": " ", "♾": " ", "⚜": " ", "⛔": " ", "❤": ".", ",": " ", "◼": " ",
                ".....": " ", "....": " ", "...": " ", "..": " ", "": " ", "": " ", "": " ", "": "", "︎": " ",
                "İ".lower(): "i", "i": "i", "ç": "c", "â": "a", "–": " ", "ş": "s", "ď": "d", "ŕ": " ", "bn": "bin",
                "✋": " ", "⬅": " ", "℅": " ", "☞": " ", "ℹ": "i", "‐": " ", "ß": "b", "™": " ",
                "war": "var}"""

    primary_letters = ["a",  # İlk önce içinde bunlardan biri geçmeyen kelimeleri direk siliyor
                       "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "u", "p", "r", "s",
                       "t", "v", "y", "z", "x", "w", "q", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9"]

    hasar_words = ["mevcut",  # bu kelimelerden herhangi birini içeriyorsa alınır
                   "bolge", "harici", "sadece", "hasar", "kay", "var", "par", "parca", "tem", "bucuk", "yok",
                   "ayri", "kaza", "olm", "leke",
                   "ac", "un", "ur", "cm", "lk", "luk", "sg", "sl", "ark", "on",
                   "hata", "kusur", "kısur", "kusır", "heta",
                   "degisen", "degsn",  "deg", "tramer", "trm", "garantili",
                   "bi", "bir", "iki", "uc", "dort", "bes",
                   "buc", "prc", "orj", "ori", "1", "1.5", "2.5", "2", "3", "4", "5", "6", "7", "8", "9",
                   "kmple", "kompile", "omp", "ump", "orda", "orada", "orta", "bel", "alti",
                   "cm",
                   "yarim", "yarm", "yrm", "yurm",
                   "lukal", "local", "lokal", "lokel", "logal", "lugal", "lkal",
                   "boya", "boy", "boyali",
                   "sok", "tak", "kapag", "kapak", "bagaj",
                   "cizik", "ciz", "ezik", "ezilme", "catl", "cetl"
                   "duzeltme", "gocuk", "goc", "duz",
                   "sol", "sul", "sag", "seg", "on", "arka", "alt", "ust",
                   "depo",
                   "kaput", "kapt", "ut", "kap",
                   "tampon", "tampn", "tanpon", "tanp", "tmp",
                   "camurluk", "cam", "camr"
                   "tavan", "tavn"
                   "marspiyer", "mars", "masp",
                   "tavn", "tava",  "kapi", "direk",
                   "sase", "sasi", "sasu", "pod", "pud", "drk", "direk", "dire",
                   "tamam",
                   ]
    exact_words = ["tl",  # direk olarak bu kelimeye eşitse alınır
                   "ve", "km"]
    remove_words = ["sahibinden",  # Bu kelimelerle aynıysa siliyor
                    "a", "b", "c", "d", "e", "f", "h", "i", "j", "l", "k", "m", "n", "o", "u",  "p", "g", "u", "t",
                    "r", "v", "y", "z", "w", "q",
                    "ad", "an"
                    "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981",
                    "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993",
                    "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005",
                    "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017",
                    "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029",
                    "2030",
                    "1.6", "1.7",
                    "1.8", "2.0", "1.9", "1.0", "1.1", "1.2", "1.3", "1.4", "park", "marka", "touch", "toch",
                    "", " ", "v1", "v2", "v3", "v4", "v5", "v6", "v7", "v8", "v9", "sacma", "otonomi",
                    "immobi̇li̇zer", "yokus", "telefon",
                    "opel",  "116d", "116i", "118d",
                    "118i", "120d", "120i", "216d", "218i", "220d",
                    "3000gt", "316ci", "316i", "316ti", "318ci", "318d", "318i", "318is", "318tds",
                    "318ti", "320cd", "320ci", "320d", "320i", "320si", "320td", "323i", "325ci", "325i", "325td",
                    "325tds", "325ti", "328ci", "328i", "330ci", "330d", "330i", "330xd", "330xi", "335i", "40th",
                    "418d", "418i", "420d", "428i", "430i", "435i", "440i", "4matic", "4motion", "4motion", "500c",
                    "500l", "518i", "520d", "520i", "520li", "523i", "524td", "525d", "525i", "525td", "525tds",
                    "525xi", "528i", "530d", "530i", "530xd", "530xi", "535d", "535i", "540i", "545i", "550d", "725d",
                    "728i", "730d", "730i", "735i", "740d", "740e", "740i", "745i", "750d", "750i", "760i", "7gtronic",
                    "9gtronic", "abarth", "accent", "access", "accord", "active", "actual", "admire", "advance",
                    "advanced", "advantage", "adventure", "ailesi", "albea", "alfa", "alhambra", "alize", "allegro",
                    "allroad", "allroad", "allstar", "allure", "almera", "altea", "altima", "alto", "ambiance",
                    "ambiante", "ambiente", "ambition", "applause", "arteon", "asphalt", "astra", "atos", "attraction",
                    "attrage", "audi", "aura", "auris", "authentique", "automatica", "automobiles", "avance",
                    "avangarde", "avant", "avantage", "avantgarde", "avensis", "aveo", "baker", "baleno", "base",
                    "basic", "basicline", "bayswater", "beats", "beetle", "benz", "berlinetta", "beymen", "bicolor",
                    "biposto", "black", "blackline", "blue", "bluebird", "bluedci", "blueefficiency",
                    "blueefficiencystart", "bluegt", "bluehdi", "bluehdi", "bluemotion", "bluetec", "bluetec", "bmax",
                    "bocanegra", "bold", "bora", "boxster", "boyut", "brava", "bravo", "break", "brera", "broadway",
                    "business", "cabrio", "cabriolet", "california", "camaro", "camry", "capital", "caprice", "caravan",
                    "carbon", "carens", "carina", "carisma", "carnival", "carrera", "cayman", "cdti", "cedition",
                    "ceed", "celica", "celysee", "cerato", "charade", "chevrolet", "chic", "chili", "choice", "chrome",
                    "chrysler", "cinquecento", "citigo", "citroën", "city", "civic", "clarus", "class", "classic",
                    "clima", "climbing", "clio", "club", "clubman", "cmax", "collection", "collozione", "color", "colt",
                    "combi", "comfort", "comfortline", "compact", "competition", "competizione", "concept", "concorde",
                    "confort", "conquest", "convertible", "cool", "cooper", "copa", "cordoba", "core", "corolla",
                    "corona", "corsa", "corvette", "cosmo", "costa", "cosworth", "country", "countryman", "coupe",
                    "crdi", "crdi", "crdivgt", "cressida", "cross", "crossfire", "crown", "cruiser", "cruze", "crystal",
                    "ctdi", "cult", "cuore", "cupra", "cvvt", "dacia", "daewoo", "daihatsu", "daimler", "darkline",
                    "dcat", "dcvvt", "ddis", "ddis", "delta", "design", "designtech", "desing", "desire", "diamond",
                    "diesel", "dinamik", "distinctive", "ditd", "ditd", "dogan", "dohc", "dolcevita", "dream", "drive",
                    "dsport", "dstyle", "dtec", "dualogic", "dynamic", "dynamique", "easy", "easyr", "echo", "eclipse",
                    "ecoboost", "ecoboost", "ecoflex", "ecomotive", "ecotsi", "edition", "editione",
                    "efficientdynamics", "egea", "ehdi", "ehybrid", "elantra", "electric", "elegance", "elegant",
                    "elite", "emgrand", "emotion", "energy", "enjoy", "envy", "epica", "escort", "espace", "espero",
                    "esprit", "essentia", "essential", "estate", "etorq", "euro", "europa", "evanda", "evasion",
                    "evolution", "excel", "excellence", "exception", "exclusive", "executive", "exeo", "expo",
                    "expression", "extra", "extreme", "fabia", "fairway", "familia", "family", "fancy", "fascination",
                    "fashion", "fastback", "favorit", "feel", "feeline", "felicia", "feline", "ferrari", "festiva",
                    "fever", "fiat", "fidji", "fiesta", "fire", "first", "flair", "flame", "flash", "flexride",
                    "fluence", "focus", "ford", "forfour", "forman", "fortwo", "ftype", "furio", "fusion", "galant",
                    "garros", "geely", "gen2", "generation", "getz", "ghia", "ghibli", "giardinetta", "giulia",
                    "giulietta", "glsi", "glxi", "goal", "gold", "golf", "grade", "gran", "grancabrio", "grand",
                    "grande", "grandis", "grandtour", "granturismo", "greentec", "griffe", "gt86", "gtdi", "gtline",
                    "gtron", "gucci", "halo", "hatchback", "high", "highline", "hiper", "hmatic", "hobby", "honda",
                    "hybrid", "hyundai", "ibiza", "icon", "iconic", "ignis", "impala", "impression", "impressive",
                    "impressor", "impreza", "indica", "indigo", "individual", "inform", "initiale", "innovation",
                    "inscription", "insignia", "instyle", "integra", "intense", "intensive", "invite", "ioniq",
                    "italia", "itech", "ivoire", "ivtec", "ix20", "jaguar", "jazz", "jetta", "john", "jump", "junior",
                    "justy", "kalina", "kalos", "kartal", "kinetic", "komp.", "konfor", "koup", "lacetti", "lada",
                    "laguna", "lancer", "lancia", "lanos", "lantis", "latino", "latitude", "laureate", "laurel",
                    "laurin&klement", "legacy", "leganza", "legend", "leon", "leone", "levorg", "liana", "liberty",
                    "life", "lifestyle", "liftback", "limited", "limousine", "line", "linea", "live", "lodgy", "logan",
                    "long", "look", "losso", "lounge", "luna", "luxe", "luxury", "m235i", "magentis", "magic", "magnus",
                    "mair", "malibu", "manager", "mans", "manza", "marea", "marina", "maruti", "maserati", "match",
                    "materia", "matiz", "matrix", "maxima", "mazda", "mcstradale", "medium", "megane", "mercedes",
                    "merit", "meriva", "micra", "midline", "millesim", "millesium", "mini", "mirai", "mirror", "mito",
                    "mitsubishi", "mjet", "mode", "modern", "modus", "momentum", "mondeo", "mood", "motion", "move",
                    "mpfi", "multiair", "multiair", "multijet", "multiwagon", "murat", "mustang", "mystic", "natty",
                    "neon", "nexia", "night", "nissan", "note", "ntec", "nubira", "octavia", "opening", "opirus",
                    "optima", "optimal", "outdoor", "paceman", "pacific", "pack", "paketi", "palio", "panamera",
                    "panaroma", "panda", "panorama", "panoramic", "passion", "pepper", "performance",
                    "performans", "peugeot", "picanto", "picasso", "picnic", "pista", "platinum", "platinyum", "play",
                    "pluriel", "plus", "plusline", "polarstar", "polo", "popstar", "popstar", "porsche", "portfolio",
                    "portfollio", "power", "practica", "prelude", "premacy", "premiere", "premio", "premium",
                    "prestige", "prestij", "previa", "pride", "prime", "primeline", "primera", "prius", "privilege",
                    "privilige", "profil", "progression", "progressive", "project", "proton", "proxy", "pulsar",
                    "pulse", "punch", "punto", "pure", "puretech", "puretech", "puzzle", "quadrifoglio", "quadrojet",
                    "quattro", "quattro", "quattroporte", "quicksilver", "racer", "rainbow", "rapid", "rapsodie",
                    "rdesign", "referance", "reference", "reflex", "renault", "rezzo", "rline", "roadster", "rockstar",
                    "roland", "romeo", "roomster", "rover", "rsport", "rtronic", "s2000", "safire", "safrane", "saloon",
                    "salt", "samara", "sandero", "saxo", "scala", "scenic", "scirocco", "scout", "scross", "scti",
                    "sdesign", "sdrive", "seat", "sebring", "sedan", "select", "selection", "selective", "selespeed",
                    "sense", "sensodrive", "sensodrive", "sephia", "serce", "serisi", "shelby", "shine", "shuma",
                    "shuttle", "sidewalk", "siena", "signature", "signo", "signum", "silver", "silverline", "sirion",
                    "skoda", "skyactived", "skyactiveg", "skyactiveg", "skyg", "skypack", "smart", "smile", "sohc",
                    "sole", "solenza", "sonata", "soul", "sovereign", "space", "spaceback", "spark", "special",
                    "speedgear", "spider", "spirit", "splash", "sport", "sportback", "sportcoupe", "sporting",
                    "sportium", "sportive", "sportivo", "sportline", "sports", "sporttourer", "sportwagon", "sportway",
                    "sporty", "spring", "sprint", "spyder", "srider", "standart", "star", "starjet", "starlet", "start",
                    "start&stop", "stella", "stepway", "stil", "still", "stilo", "stinger", "stratus", "stream",
                    "street", "streetwise", "stylance", "style", "stype", "subaru", "sunny", "super", "superb",
                    "superfast", "supra", "suzuki", "svti", "swift", "swing", "sxie", "symbol", "şahin", "talisman",
                    "targa", "tata", "taunus", "taycan", "tdci", "tdci", "team", "teana", "technic", "techno",
                    "technology", "technoplus", "techroad", "tekna", "tekno", "tempra", "terra", "tfsi", "tgdi",
                    "thema", "tico", "tigra", "tipo", "titanium", "tivct", "tjet", "tjet", "tofas", "toledo", "toros",
                    "touch", "touchrome", "tour", "tourer", "touring", "toyota", "trajet", "trend", "trendline",
                    "trendy", "tributo", "troy", "tune", "turbo", "turismo", "turkiye", "twin", "twinair", "twingo",
                    "twinport", "typer", "types", "ultimate", "urban", "variant", "vario", "vectra", "vega", "veloce",
                    "venga", "verde", "verso", "vignale", "viii", "visia", "visio", "vision", "vista", "vites", "vites",
                    "viva", "vivio", "volkswagen", "volvo", "vtec", "vtec", "vtrpk", "vvti", "wagon", "waja", "weekend",
                    "white", "wind", "window", "winter", "works", "world", "wtcc", "xantia", "xcellence", "xdesign",
                    "xdrive", "xedos", "xline", "xpack", "xperience", "xr2i", "xr3i", "xrdt", "xsara", "xtrend",
                    "xtype", "yaris", "year", "yearling", "years", "ypsilon", "zafira", "as", "az", "bedel", "bela",
                    "beladan", "belaasi", "belalardan", "belali", "belalilar", "beld", "belde"
                    ]

    baslamasin = ["akab", "akli", "adj", "abi", "adil", "aile", "adab", "adap", "acik", "acig", "aday", "adj", "adi",
                  "aci", "act", "acr", "acu", "aco", "acc", "abs", "aca", "ace", "aba", "abe", "abo", "abu", "adv",
                  "aga", "acm", "acr", "ada", "adb", "adc", "add", "adm", "ae", "af", "aguc", "ait", "aka", "akb",
                  "akc", "akg", "aki", "akl", "akr", "aksi", "aktar", "akt", "aku", "ala", "alb", "alc", "ald", "ale",
                  "alg", "ali", "alk", "alla", "alls", "allc", "allu", "alm", "alo", "alp", "alu", "ama", "amb", "amc",
                  "ame", "amf", "amg", "amor", "amp", "amon", "ana", "anb", "anc", "and", "anf", "anh", "ani", "ank",
                  "anl", "ano", "ant", "aon", "aor", "ap", "aq", "arab", "arac", "arad", "arag", "aral", "aram",
                  "aran", "arar", "aras", "arav", "aray", "arb", "ard", "are", "arg", "ariy", "aric", "arkadas",
                  "arkads",  "arkam", "arkap", "arkao", "aro", "ars", "art", "ary", "asf", "asg", "asi", "ask",
                  "asl", "asr", "ast", "asv", "asy", "at", "au", "ava", "avc", "avm", "avo", "avr", "avus", "ay",
                  "aza", "azb", "azd", "azi", "bab",
                  "bad", "bagi", "bagl", "bah", "bai", "bak", "balan", "balat", "balc", "bale", "bali", "balk",
                  "balo", "bals", "balt", "bam", "ban", "bar", "basi", "basa", "baski", "basl", "bast", "basu",
                  "basv", "bat", "bayan", "bayaz", "bayi", "bayk", "bayr", "bays", "bayt", "baza", "baze", "bazk",
                  "bbs", "bc", "bea", "bedeli", "begen", "beg", "bei", "bej", "bekl", "belam", "belas", "belay", "belc",
                  "beldel", "beldes", "beldi", "bele", "belg", "belh", "beli", "belk", "bella", "belle", "belli",
                  "ben", "ber", "bert", "bese", "besi", "besk", "besl", "besn", "best", "bet", "bex", "bey", "bia",
                  "bib", "bic", "bid", "bie", "big", "bii", "bij", "bikad", "bikar", "bike", "bikg", "biki", "bikk",
                  "bikm", "bikt", "biku", "bil", "bile", "bilf", "bilg", "bilh", "bili", "bilk", "bill", "bilm",
                  "biln", "bilo", "bilq", "bilr", "bils", "bilt", "bilun", "bily", "bilz", "bim", "binc", "binde",
                  "bindi", "bine", "bini", "bink", "binl", "binm", "binn", "bio", "bira", "birbir", "birc", "bire",
                  "birf", "birg", "birh", "biri", "birl", "birm", "birn", "biro", "birp", "birs", "biru", "biryi",
                  "birz", "bis", "bit", "bix", "biyasa", "biyik", "biyo", "biz", "bk", "bj", "bl", "bm", "bn", "bob",
                  "bolm", "bolu", "bom", "bon", "bor", "bos", "bot", "bou", "boz", "bp", "br", "bs", "bt", "bug", "buh",
                  "buj", "buk", "bul", "bun", "buo", "bur", "but", "buy", "buz", "bv", "bx", "by",
                  "cab", "cad", "cag", "cak", "cal", "can", "cap", "cao",
                  "car", "cas", "cay", "cax", "caz", "cb", "cd", "ce", "cf", "cg", "ch", "cic", "cid", "cif", "cig",
                  "cih", "cii", "cik", "cil", "cim", "cin", "cis", "cit", "civ", "cj", "ck", "cl", "cm2", "cm3", "cmg",
                  "cmj", "cmk", "cml", "cmo", "cmp", "cms", "cmt", "cmuz", "cmy", "co", "cp", "cr", "cs", "cs", "ct",
                  "cu", "cv", "cx", "cy", "dab", "dac",
                  "daf", "dag", "dah", "dai", "dak", "dam", "dan", "dara", "dark", "dat", "das", "dav", "day", "db",
                  "dc", "dea", "deb", "dec", "def", "degd", "dega", "deger", "degil", "dek", "del", "dem", "den",
                  "dep", "der", "dest", "det", "dev", "dex", "dez", "df", "dij", "dik", "dil", "din", "diri", "dis",
                  "diy", "diz", "dj", "dk", "dl", "dm", "do", "dn", "dold", "dolm", "don", "dop", "dos", "dou", "dov",
                  "dow", "doy", "dp", "dq", "dreks", "dri", "ds", "dub", "duc", "dug", "duk", "dum", "dun", "dur",
                  "dus", "duv", "duy", "duzg", "dv", "dy", "dz",
                  "ea", "eb", "ec", "ed", "ee", "ef", "eg", "eh", "ej", "ek", "el", "em", "en", "eo", "ep", "eq",
                  "er", "es", "etem", "etik", "ett", "eu", "ev", "ex", "ey",
                  "faa", "fab", "fac", "fai", "fak", "fal", "fan", "fao", "fap", "farb", "fark",
                  "fas", "fat", "fav", "fay", "faz", "fb", "fc", "fd", "fe", "ff", "fi", "fl", "fn", "fm", "fo", "fp",
                  "fr", "fs", "ft", "fu", "fx", "fy", "fz", "ga", "gb", "gc", "gd", "ge", "gf", "gg", "gh", "gi", "gk",
                  "gl", "gm", "gn", "god", "gog", "gok", "gol", "gon", "gor", "gos", "got", "goz", "gp", "gr", "gs",
                  "gt", "gu", "hab", "hac", "had", "haf", "hak", "hall", "halk", "halt", "ham", "han", "hap", "harc",
                  "harik", "harm", "harv", "hassa", "hast", "hat", "hav", "hay", "haz", "hb", "hel", "hem", "herk",
                  "hers", "hery", "hes", "hex", "hez", "hi", "ho", "hp", "hu", "hx", "hy", "ib", "ic", "id", "ie", "ig",
                  "ih", "ii", "il", "im", "ind", "ine", "inf", "ini", "inj", "inm", "inn", "ino", "ins", "int", "io",
                  "ip", "ir", "iso", "isp", "isr", "ist", "isu", "isy", "it", "iu", "iv", "iw", "ix", "iy", "iz", "j",
                  "kabi", "kac", "kade", "kadi", "kado", "kadr", "kaf", "kah", "kal", "kam", "kan", "kapal", "kapam",
                  "kapan", "kapas", "kapat", "kapay", "kapl", "kapta", "kapti", "kapto", "kaptu", "kara", "karb",
                  "kard", "kark", "karl", "karp", "kars", "kart", "kasa", "kase", "kasi", "kast", "kat", "kau",
                  "kav", "kaya", "kayb", "kayf", "kayg", "kayh", "kayin", "kayip", "kayis", "kayl", "kaym", "kays",
                  "kayz", "kd", "ken", "ker", "keb", "kel", "kem", "key", "kez", "kg", "kh", "kil", "kim", "kisa",
                  "kisis", "kisl", "kit", "kiy", "kiz", "kl", "km", "kn", "kok", "kol", "kombin", "koms", "kon", "koon",
                  "koor", "kor", "kos", "kot", "koy", "koz", "kr", "kt", "kul", "kua", "kub", "kum", "kup", "kur",
                  "kus", "kut", "kuy", "kuv", "kuz", "kw", "ky", "la", "led", "len", "leo", "let", "lev", "li", "ll",
                  "lm", "lon", "los", "lov", "ls", "lt", "lut", "lux", "ly", "maa", "mah", "mag", "mad", "mak", "mal",
                  "man", "mark", "mart", "masra", "mat", "mav", "may", "maz", "mb", "mc", "md", "meb", "med", "meg",
                  "mek", "mel", "mem", "men", "mer", "mes", "met", "mez", "mf", "mh", "mi", "mj", "mk", "ml", "mo",
                  "mp", "mt", "mu", "my", "mx", "mz", "na", "nb", "nc", "nd", "ne", "ni", "nj", "nk", "nl", "nm", "no",
                  "nu", "nw", "oa", "ob", "oc", "od", "of", "og", "ok", "olab", "olag", "olam", "olan", "olc", "old",
                  "olm", "ols", "om", "onay", "one", "onf", "ong", "onl", "onp", "onr", "onum", "onun", "onur", "onya",
                  "ooo", "op", "ortal", "ortam", "ortao", "ortap", "ortas", "ortu", "oru", "os", "oy", "oz", "pab",
                  "pak", "pai", "pac", "pah", "pak", "pal", "pan", "pap", "pard", "parf", "pari", "parl", "park",
                  "parm", "parn", "paro", "parp", "part", "parz", "pas", "pat", "paz", "pc", "pd", "pe", "pf", "ph",
                  "pi", "pj", "pk", "pl", "pn", "pol", "pom", "pos", "pow", "pov", "pre", "pri", "pro", "ps", "pt",
                  "pv", "pw", "py", "q", "r", "sab", "sac", "saf", "sah", "sai", "sak", "sal", "san", "sar", "sat",
                  "say", "sb", "sc", "seg", "sel", "seh", "sec", "seb", "sem", "sen", "ser", "ses", "sev", "sey",
                  "sez", "sf", "sg", "sh", "si", "sk", "sl", "sm", "sn", "son", "soo", "sor", "sop", "sot", "sov",
                  "soy", "sow", "soz", "sp", "sr", "st", "sua", "sub", "suc", "suk", "sul", "sun", "sup", "suo",
                  "suru", "sure", "sura", "surg", "surr", "sus", "suv", "suz", "sv", "sw", "sx", "sy", "tab", "tac",
                  "tad", "tah", "tai", "tak", "tal", "tar", "tas", "tat", "tau", "tay", "tb", "td", "tc", "tec", "tee",
                  "ted", "tef", "tel", "temin", "temen", "temel", "temm", "temn", "temp", "tems", "temu", "ten", "ter",
                  "tes", "tet", "tev", "tey", "tez", "tf", "th", "ti", "tl", "tok", "tof", "ton", "too", "tor", "tou",
                  "toy", "toz", "tp", "trab", "traf", "trak", "tran", "tri", "trn", "tro", "trp", "tru", "trx", "ts",
                  "tu", "tw", "tx", "ty", "uca", "ucc", "ucd", "uce", "ucg", "uci", "uck", "ucl", "ucm", "ucn", "uco",
                  "ucr", "ucs", "uct", "ucu", "ud", "uf", "ug", "ul", "um", "un", "up", "ur", "us", "ut", "uu", "uy",
                  "uz",  "vak", "vab", "vad", "vag", "val", "van", "vara", "vare", "vari", "varl", "varm", "varo",
                  "vary", "vas", "vat", "vaz", "vb", "vc", "ver", "vf", "vi", "vj", "vk", "vl", "vo", "vp", "vr",
                  "vs", "vt", "vu", "vw", "w", "x", "yap", "yas", "yat", "yay", "yaz", "yb", "yd", "yede", "yek",
                  "yel", "yem", "yen", "yep", "yer", "yig", "yik", "yil", "yip", "yog", "yo", "yp", "ys", "yu", "yy",
                  "za", "ze", "zf", "zl", "zo", "zr", "zx", "zy"

                  ]

    hasar_unwanted_words = ["sahib",  # Bu kelimelerden herhangi birini içeriyorsa siliyor
                            "lpg", "pesin", "foto", "fotu", "iletisim", "sabit", "tele", "takas",
                            "1hp", "2hp", "3hp", "4hp", "5hp", "6hp", "7hp", "8hp", "9hp", "0hp",
                            "1km", "2km", "3km", "4km", "5km", "6km", "7km", "8km", "9km", "0km", "onc", "mp3",
                            "0de", "1de", "2de", "3de", "4de", "5de", "6de", "7de", "8de", "9de",
                            "0ps", "1ps", "2ps", "3ps", "4ps", "5ps", "6ps", "7ps", "8ps", "9ps",
                            "0nm", "1nm", "2nm", "3nm", "4nm", "5nm", "6nm", "7nm", "8nm", "9nm",
                            "0cc", "1cc", "2cc", "3cc", "4cc", "5cc", "6cc", "7cc", "8cc", "9cc",
                            "bit.ly",
                            "oto", "lgp",
                            "pavyon", "patron", "pasta", "passat", "paspas", "parla", "park",
                            ]

    numbers = ["053", "054", "055", "050", "0.53", "0.54", "0.55", "0.50", "9053", "9054", "9055", "9050",
               "322", "416", "272", "472", "382", "358", "312", "242", "478", "466", "256", "266", "378", "488",
               "458", "228", "426", "434", "374", "248", "224", "286", "376", "364", "258", "412", "284", "424",
               "446", "442", "222", "342", "454", "456", "438", "326", "476", "246", "324", "212", "232", "344",
               "370", "338", "474", "366", "352", "318", "288", "386", "342", "262", "332", "274", "422", "236",
               "482", "252", "436", "384", "388", "452", "464", "264", "362", "484", "368", "346", "414", "486",
               "282", "356", "462", "428", "276", "432", "226", "354", "372", "216",

               "532", "539", "531", "533", "534", "535", "536", "537", "538",
               "554", "555", "558", "557", "551", "550", "552", "553", "559",
               "505", "506", "507",

               "90322", "90416", "90272", "90472", "90382", "90358", "90312", "90242", "90478", "90466", "90256",
               "90266", "90378", "90488", "90458", "90228", "90426", "90434", "90374", "90248", "90224", "90286",
               "90376", "90364", "90258", "90412", "90284", "90424", "90446", "90442", "90222", "90342", "90454",
               "90456", "90438", "90326", "90476", "90246", "90324", "90212", "90232", "90344", "90370", "90338",
               "90474", "90366", "90352", "90318", "90288", "90386", "90342", "90262", "90332", "90274", "90422",
               "90236", "90482", "90252", "90436", "90384", "90388", "90452", "90464", "90264", "90362", "90484",
               "90368", "90346", "90414", "90486", "90282", "90356", "90462", "90428", "90276", "90432", "90226",
               "90354", "90372", "90216",
               "0322", "0416", "0272", "0472", "0382", "0358", "0312", "0242", "0478", "0466", "0256",
               "0266", "0378", "0488", "0458", "0228", "0426", "0434", "0374", "0248", "0224", "0286",
               "0376", "0364", "0258", "0412", "0284", "0424", "0446", "0442", "0222", "0342", "0454",
               "0456", "0438", "0326", "0476", "0246", "0324", "0212", "0232", "0344", "0370", "0338",
               "0474", "0366", "0352", "0318", "0288", "0386", "0342", "0262", "0332", "0274", "0422",
               "0236", "0482", "0252", "0436", "0384", "0388", "0452", "0464", "0264", "0362", "0484",
               "0368", "0346", "0414", "0486", "0282", "0356", "0462", "0428", "0276", "0432", "0226",
               "0354", "0372", "0216"
               ]

    # baslamasin = ["akab"]
    return hasar_words, exact_words, remove_words, replaces, hasar_unwanted_words, numbers, baslamasin, primary_letters, alphabet
